# Generated by Django 6.0 on 2025-12-10 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TonalidadeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonalidade_1', models.IntegerField(default=50)),
                ('tonalidade_2', models.IntegerField(default=50)),
                ('tonalidade_3', models.IntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tonalidade_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
